---
#
# var:cloud
# var:bucket
# var:key
# var:secret
# var:software
# var:swap
# var:root
#
- name: Prep database host
  hosts: all
  gather_facts: no
  roles:
    - add-oracle-account
    - install-sw-packages
    - install-db-package
    - copy-software
    - { role: make-swap, when: swap is defined and swap != '' }
